#!/bin/bash
git --work-tree=/webapps/hello/repo --git-dir=/webapps/hello/bare checkout -f

# activate virtualenv
source /webapps/hello/env/bin/activate

cd /webapps/hello/repo
pip install -r requirements.txt

# replace ukroptest_django with staging or ukroppen production env name
find . -type f -name "*" -exec sed -i "s/ukroptest_django/hello/g" "{}" \;
find . -type f -name "*" -exec sed -i "s/ukroptest/hello/g" "{}" \;
find . -type f -name "*" -exec sed -i "s/ukroppen_django/hello/g" "{}" \;
#cd ukroppen
#python manage.py migrate
#python manage.py compilemessages
#python manage.py collectstatic --noinput

#sudo supervisorctl restart hello
